server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=interop
    username: postgres
    password: admin

  batch:
    initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    arg:
      hibernate:
        SQL: DEBUG

